branches:
  except:
  - "/^wip/"
language: node_js
node_js: '10'
env:
  global:
  - COVERALLS_PARALLEL=true
jobs:
  include:
    -
      name: "Unit Tests"
      install:
      - travis_retry yarn
      script:
      - yarn lint
      - TZ="America/Los_Angeles" yarn nyc node ./test/unit main universe
      after_success: yarn run coverage
    -
      name: "Scenario Tests"
      install:
      - travis_retry yarn
      script:
      - TZ="America/Los_Angeles" yarn nyc node ./test/scenarios -r universe builtin main universe
      after_success: yarn run coverage
    -
      name: "Dataset Generation"
      install:
      - travis_retry yarn
      - pyenv global 3.6.7
      - pip3 install --user numpy
      script:
      - ./travis/test-dataset.sh

notifications:
  webhooks: https://coveralls.io/webhook
