branches:
  except:
  - "/^wip/"
language: node_js
node_js: '10'
env:
  global:
  - COVERALLS_PARALLEL=true
jobs:
  include:
    -
      name: "Unit Tests"
      script:
      - npm run lint
      - TZ="America/Los_Angeles" npx nyc node ./test/unit main universe
      after_success: npm run coverage
    -
      name: "Scenario Tests"
      script:
      - TZ="America/Los_Angeles" npx nyc node ./test/scenarios -r universe builtin main universe
      after_success: npm run coverage
    -
      name: "Dataset Generation"
      script:
      - ./travis/test-dataset.sh

notifications:
  webhooks: https://coveralls.io/webhook
